create table endereco
(
    id         bigint generated by default as identity,
    bairro     varchar(255),
    cep        varchar(255),
    cidade     varchar(255),
    estado     varchar(255),
    logradouro varchar(255),
    numero     bigint,
    primary key (id)
)