create table usuario
(
    id               bigint generated by default as identity,
    data_atualizacao timestamp(6),
    data_criacao     timestamp(6),
    email            varchar(255),
    login            varchar(255),
    nome             varchar(255),
    senha            varchar(255),
    tipo_usuario     varchar(255) check (tipo_usuario in ('ADMIN', 'CLIENTE', 'DONO_RESTAURANTE')),
    endereco_id      bigint,
    primary key (id)
);

alter table if exists usuario add constraint FK8fl5dxscva53gw12f19q6qxf8 foreign key (endereco_id) references endereco;