create table dia
(
    id                 bigint generated by default as identity,
    aberto             boolean,
    data_atualizacao   timestamp(6),
    data_criacao       timestamp(6),
    horario_abertura   varchar(255),
    horario_fechamento varchar(255),
    nome               varchar(255) check (nome in ('SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO', 'DOMINGO')),
    primary key (id)
)

