create table restaurante
(
    id                       bigint generated by default as identity,
    data_atualizacao         timestamp(6) not null,
    data_criacao             timestamp(6) not null,
    nome                     varchar(255) not null,
    tipo_cozinha             varchar(255) not null,
    endereco_id              bigint,
    horario_funcionamento_id bigint,
    usuario_id               bigint,
    primary key (id)
);


alter table if exists restaurante drop constraint if exists UKki5no6idqiaah4ps02myos733;
alter table if exists restaurante add constraint UKki5no6idqiaah4ps02myos733 unique (endereco_id);

alter table if exists restaurante drop constraint if exists UKgxfu9yan0w5wr5phva4w8i925;
alter table if exists restaurante add constraint UKgxfu9yan0w5wr5phva4w8i925 unique (horario_funcionamento_id);

alter table if exists restaurante drop constraint if exists UK5n2bxu5cw8vg71uk5sepo20wo;
alter table if exists restaurante add constraint UK5n2bxu5cw8vg71uk5sepo20wo unique (usuario_id);

alter table if exists restaurante add constraint FKnc0aps7r9c6euyqrs6d2v04qa foreign key (endereco_id) references endereco;
alter table if exists restaurante add constraint FK453hcuvd2mpyxpb3ganlicqq9 foreign key (horario_funcionamento_id) references horario_funcionamento;
alter table if exists restaurante add constraint FKbc8qnjwp8ljjv48ebhws7w4hu foreign key (usuario_id) references usuario;
