-- V1__create_tables.sql

CREATE TABLE endereco (
                          id bigint GENERATED BY DEFAULT AS IDENTITY,
                          bairro varchar(255),
                          cep varchar(255),
                          cidade varchar(255),
                          estado varchar(255),
                          logradouro varchar(255),
                          numero bigint,
                          PRIMARY KEY (id)
);

CREATE TABLE horario_funcionamento (
                                       id bigint GENERATED BY DEFAULT AS IDENTITY,
                                       data_atualizacao timestamp(6),
                                       data_criacao timestamp(6),
                                       dom_aberto boolean,
                                       dom_abertura varchar(255),
                                       dom_fechamento varchar(255),
                                       qua_aberto boolean,
                                       qua_abertura varchar(255),
                                       qua_fechamento varchar(255),
                                       qui_aberto boolean,
                                       qui_abertura varchar(255),
                                       qui_fechamento varchar(255),
                                       sab_aberto boolean,
                                       sab_abertura varchar(255),
                                       sab_fechamento varchar(255),
                                       seg_aberto boolean,
                                       seg_abertura varchar(255),
                                       seg_fechamento varchar(255),
                                       sext_aberto boolean,
                                       sext_abertura varchar(255),
                                       sext_fechamento varchar(255),
                                       ter_aberto boolean,
                                       ter_abertura varchar(255),
                                       ter_fechamento varchar(255),
                                       PRIMARY KEY (id)
);

CREATE TABLE prato (
                       id bigint GENERATED BY DEFAULT AS IDENTITY,
                       apenas_no_local boolean,
                       data_de_atualizacao timestamp(6),
                       data_de_criacao timestamp(6),
                       descricao varchar(255),
                       foto_do_prato varchar(255),
                       nome varchar(255),
                       preco numeric(38,2),
                       restaurante_id bigint NOT NULL,
                       PRIMARY KEY (id)
);

CREATE TABLE restaurante (
                             id bigint GENERATED BY DEFAULT AS IDENTITY,
                             data_atualizacao timestamp(6) NOT NULL,
                             data_criacao timestamp(6) NOT NULL,
                             nome varchar(255) NOT NULL,
                             tipo_cozinha varchar(255) NOT NULL,
                             endereco_id bigint NOT NULL,
                             horario_funcionamento_id bigint NOT NULL,
                             usuario_id bigint NOT NULL,
                             PRIMARY KEY (id)
);

CREATE TABLE usuario (
                         id bigint GENERATED BY DEFAULT AS IDENTITY,
                         data_atualizacao timestamp(6),
                         data_criacao timestamp(6),
                         email varchar(255),
                         login varchar(255),
                         nome varchar(255),
                         senha varchar(255),
                         tipo_usuario varchar(255) CHECK (tipo_usuario IN ('ADMIN','CLIENTE','DONO_RESTAURANTE')),
                         endereco_id bigint,
                         PRIMARY KEY (id)
);