create table horario_funcionamento
(
    id               bigint generated by default as identity,
    data_atualizacao timestamp(6),
    data_criacao     timestamp(6),
    domingo_id       bigint,
    quarta_id        bigint,
    quinta_id        bigint,
    sabado_id        bigint,
    segunda_id       bigint,
    sexta_id         bigint,
    terca_id         bigint,
    primary key (id)
);

alter table if exists horario_funcionamento drop constraint if exists UKr6l1m6x9y5v3z7q1w2e3r4t5u;
alter table if exists horario_funcionamento add constraint UKr6l1m6x9y5v3z7q1w2e3r4t5u unique (segunda_id);

alter table if exists horario_funcionamento drop constraint if exists UKb1c2d3e4f5g6h7i8j9k0l1m2n3;
alter table if exists horario_funcionamento add constraint UKb1c2d3e4f5g6h7i8j9k0l1m2n3 unique (terca_id);

alter table if exists horario_funcionamento drop constraint if exists UK6tc6d50nh0d8vrcwhtl6bf7bu;
alter table if exists horario_funcionamento add constraint UK6tc6d50nh0d8vrcwhtl6bf7bu unique (quarta_id);

alter table if exists horario_funcionamento drop constraint if exists UKftn3avcj72nxg9bjrky93otth;
alter table if exists horario_funcionamento add constraint UKftn3avcj72nxg9bjrky93otth unique (quinta_id);

alter table if exists horario_funcionamento drop constraint if exists UKj8k9l0m1n2o3p4q5r6s7t8u9v;
alter table if exists horario_funcionamento add constraint UKj8k9l0m1n2o3p4q5r6s7t8u9v unique (sexta_id);

alter table if exists horario_funcionamento drop constraint if exists UK6m3gk1p6y2p6r4h5v6j8o4n9;
alter table if exists horario_funcionamento add constraint UK6m3gk1p6y2p6r4h5v6j8o4n9 unique (sabado_id);

alter table if exists horario_funcionamento drop constraint if exists UKp14kid8qyrqydoj8seecxiyku;
alter table if exists horario_funcionamento add constraint UKp14kid8qyrqydoj8seecxiyku unique (domingo_id);

alter table if exists horario_funcionamento add constraint FKojvvkhm5vbp58hau0rlqwd2rn foreign key (segunda_id) references dia;
alter table if exists horario_funcionamento add constraint FK56tx2rxbh48dr9de48uh65e7y foreign key (terca_id) references dia;
alter table if exists horario_funcionamento add constraint FKr09qb6tkll4e3ba2l7097fxcl foreign key (quarta_id) references dia;
alter table if exists horario_funcionamento add constraint FKadybe9643x473nw4fnenmbsbc foreign key (quinta_id) references dia;
alter table if exists horario_funcionamento add constraint FK5es4b7rlfdi5k9etohmeqpd62 foreign key (sexta_id) references dia;
alter table if exists horario_funcionamento add constraint FKgc8ubd9wvg0w6ldip3w8w5uxb foreign key (sabado_id) references dia;
alter table if exists horario_funcionamento add constraint FKtmmeiy38ycoioj317qn753sof foreign key (domingo_id) references dia;


